services:
  - type: web
    name: utamu-agency-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        value: 11monari72dan
      - key: DATA_DIR
        value: /var/data
    disk:
      name: utamu-data
      mountPath: /var/data
      sizeGB: 1
